sudo: false
notifications:
  email: false
branches:
  only:
  - gh-pages
  - master
language: rust
cache: cargo
rust:
  - stable
install:
  - (cargo install mdbook || true)
script:
  - bash ci/build.sh
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: gh-pages
